import "./Footer.css";

const Footer = () => {

  return (
    <footer className="footer">
      <p className='footer-text'>The information on this website is generated by AI technology and is not legal advice. It is intended for general informational and entertainment purposes only.</p>
    </footer>
  )
};

export default Footer;
