import "./Footer.css";

const Footer = () => {

  return (
    <footer className="footer">
      <p className='footer-text'>The information provided on this website is generated by third party AI technology and does not constitute legal advice. All content on this site is intended for general informational and entertainment purposes only.</p>
    </footer>
  )
};

export default Footer;
